### ISSUE TITLE
Fix broken build

### ISSUE THREAD

**Issue by impredicative** [awslabs/datawig#115]
Why is the failing build not been fixed? Is the project still alive? It hasn't seen any updates lately. Or is it abandoned?

**Comment by felixbiessmann** [comment]
thanks for raising this issue! and yes, the project is still alive and the [build has been working fine until last week](https://travis-ci.org/awslabs/datawig/builds) but since 6 days there seem to be some file system permission issues on the build host and some tests started failing. 

We'll look into it asap.

**Comment by felixbiessmann** [comment]
[This backwards incompatible API change in pandas](https://github.com/pandas-dev/pandas/pull/30103) in the latest [pandas version 1.0.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html#backwards-incompatible-api-changes) released on Jan 29 appears to have broken the subsequent builds. 

In the latest build the [tests are working again](https://travis-ci.com/awslabs/datawig/builds/147844971)
