### ISSUE TITLE
Save learning curve in metrics

### ISSUE THREAD

**Issue by TammoR** [awslabs/datawig#19]
I would propose to write learning curve as part of the metrics output. I.e. log likelihood, test and train accuracy; all as function of the epoch. This facilitates convergence diagnostics and is computed already.

**Comment by felixbiessmann** [comment]
sounds good to me. i think i had it in one version like that, but then the epochs and in particular the index of the best one is needed for the deserialization of the mxnet parameters. so that information must be available in some form when loading the imputer. 
but the entire metrics file can become very large, e.g. with a large number of labels. so having the entire metrics object as a field of the imputer would be impractical.

**Comment by felixbiessmann** [comment]
I still think that it would be good to have that information as part of the imputer, for the above mentioned reasons. But as long as the model can still be de/serialized, i guess it's fine to save that in other places, too?

**Comment by TammoR** [comment]
This is solved.
