### ISSUE TITLE
Problems during installation and execution of example code

### ISSUE THREAD

**Issue by sscdotopen** [awslabs/datawig#31]
Hi,

I installed datawig today using pip3 in an extra virtualenv and ran into some problems that I'd like to point out here.

During the installation, I encountered the following warning:
`mxnet 1.3.0b20180820 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.15.0 which is incompatible.`

After importing numpy in jupyter I got this warning:

```
/home/.../datawig/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```

Next I tried the simple imputer example, but the `fit_hpo` method took ages to run for the small train dataset with 5k records, I stopped the hpo after 20 minutes or so.

When I tried to evaluate the predictions of datawig using the proposed code
`f1 = f1_score(predictions['finish'], predictions['finish_imputed'])`

I received the following error message:

`ValueError: Target is multiclass but average='binary'. Please choose another average setting.`

**Comment by felixbiessmann** [comment]
As for the mxnet numpy version incompatibility: i got that warning too when I last checked (some weeks ago), but all tests ran through. 
As for the long run time for hpo: could be related to some overly generous hp choices in the default args?

-------- Ursprüngliche Nachricht --------Von: Sebastian <notifications@github.com> Datum: 26.09.18  20:45  (GMT+01:00) An: awslabs/datawig <datawig@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [awslabs/datawig] Problems during installation and execution of example code (#31) 
Hi,
I installed datawig today using pip3 in an extra virtualenv and ran into some problems that I'd like to point out here.
During the installation, I encountered the following warning:

mxnet 1.3.0b20180820 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.15.0 which is incompatible.
After importing numpy in jupyter I got this warning:
/home/.../datawig/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

Next I tried the simple imputer example, but the fit_hpo method took ages to run for the small train dataset with 5k records, I stopped the hpo after 20 minutes or so.
When I tried to evaluate the predictions of datawig using the proposed code

f1 = f1_score(predictions['finish'], predictions['finish_imputed'])
I received the following error message:
ValueError: Target is multiclass but average='binary'. Please choose another average setting.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/awslabs/datawig","title":"awslabs/datawig","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/awslabs/datawig"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Problems during installation and execution of example code (#31)"}],"action":{"name":"View Issue","url":"https://github.com/awslabs/datawig/issues/31"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/awslabs/datawig/issues/31",
"url": "https://github.com/awslabs/datawig/issues/31",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Problems during installation and execution of example code (#31)",
"sections": [
{
"text": "",
"activityTitle": "**Sebastian**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sscdotopen",
"facts": [
{
"name": "Repository: ",
"value": "awslabs/datawig"
},
{
"name": "Issue #: ",
"value": 31
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"awslabs/datawig\",\n\"issueId\": 31,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"awslabs/datawig\",\n\"issueId\": 31\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/awslabs/datawig/issues/31"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 384634304\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sscdotopen** [comment]
Maybe we should tell users to ignore the warning w.r.t. numpy, it took me a while to figure out that it works despite the warning.

The long runtime for the HPO could cause a negative impact for people trying datawig, maybe we should only show an invocation of fit_hpo with settings that finish in reasonable time.

**Comment by TammoR** [comment]
Did your hpo dataset have numeric inputs?

**Comment by sscdotopen** [comment]
Didn't check, I just used the example dataset linked to in the post :)
